// <auto-generated />
using System;
using MCT.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MCT.Migrations
{
    [DbContext(typeof(MctContext))]
    partial class MctContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MCT.Models.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("match_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MatchId"));

                    b.Property<string>("MatchType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("match_type");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<int?>("ScoreA")
                        .HasColumnType("integer")
                        .HasColumnName("score_a");

                    b.Property<int?>("ScoreB")
                        .HasColumnType("integer")
                        .HasColumnName("score_b");

                    b.Property<int>("TeamAId")
                        .HasColumnType("integer")
                        .HasColumnName("team_a_id");

                    b.Property<int>("TeamBId")
                        .HasColumnType("integer")
                        .HasColumnName("team_b_id");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer")
                        .HasColumnName("tournament_id");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("integer")
                        .HasColumnName("winner_id");

                    b.HasKey("MatchId")
                        .HasName("matches_pkey");

                    b.HasIndex("MatchType");

                    b.HasIndex("TeamAId");

                    b.HasIndex("TeamBId");

                    b.HasIndex("TournamentId");

                    b.HasIndex("WinnerId");

                    b.ToTable("matches", (string)null);
                });

            modelBuilder.Entity("MCT.Models.MatchType", b =>
                {
                    b.Property<string>("TypeName")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("type_name");

                    b.HasKey("TypeName")
                        .HasName("match_types_pkey");

                    b.ToTable("match_types", (string)null);
                });

            modelBuilder.Entity("MCT.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("payment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_date");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int?>("TicketId")
                        .HasColumnType("integer")
                        .HasColumnName("ticket_id");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("transaction_id");

                    b.HasKey("PaymentId")
                        .HasName("payments_pkey");

                    b.HasIndex("Status");

                    b.HasIndex("TicketId");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("MCT.Models.PaymentStatus", b =>
                {
                    b.Property<string>("StatusName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status_name");

                    b.HasKey("StatusName")
                        .HasName("payment_statuses_pkey");

                    b.ToTable("payment_statuses", (string)null);
                });

            modelBuilder.Entity("MCT.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlayerId"));

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("PlayerId")
                        .HasName("players_pkey");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("MCT.Models.Stat", b =>
                {
                    b.Property<int>("StatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("stat_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatId"));

                    b.Property<int?>("Assists")
                        .HasColumnType("integer")
                        .HasColumnName("assists");

                    b.Property<int?>("Deaths")
                        .HasColumnType("integer")
                        .HasColumnName("deaths");

                    b.Property<decimal?>("HsPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("hs_percentage");

                    b.Property<int?>("Kills")
                        .HasColumnType("integer")
                        .HasColumnName("kills");

                    b.Property<int?>("MatchId")
                        .HasColumnType("integer")
                        .HasColumnName("match_id");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.HasKey("StatId")
                        .HasName("stats_pkey");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.ToTable("stats", (string)null);
                });

            modelBuilder.Entity("MCT.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TeamId"));

                    b.Property<int?>("MemberCount")
                        .HasColumnType("integer")
                        .HasColumnName("member_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("region");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("short_code")
                        .IsFixedLength();

                    b.HasKey("TeamId")
                        .HasName("teams_pkey");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("MCT.Models.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ticket_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TicketId"));

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchase_date");

                    b.Property<string>("QrCode")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("qr_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer")
                        .HasColumnName("tournament_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("TicketId")
                        .HasName("tickets_pkey");

                    b.HasIndex("Status");

                    b.HasIndex("TournamentId");

                    b.HasIndex("UserId");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("MCT.Models.TicketStatus", b =>
                {
                    b.Property<string>("StatusName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status_name");

                    b.HasKey("StatusName")
                        .HasName("ticket_statuses_pkey");

                    b.ToTable("ticket_statuses", (string)null);
                });

            modelBuilder.Entity("MCT.Models.Tournament", b =>
                {
                    b.Property<int>("TournamentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tournament_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TournamentId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("location");

                    b.Property<int>("Places")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("TournamentId")
                        .HasName("tournaments_pkey");

                    b.HasIndex("Status");

                    b.ToTable("tournaments", (string)null);
                });

            modelBuilder.Entity("MCT.Models.TournamentStatus", b =>
                {
                    b.Property<string>("StatusName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status_name");

                    b.HasKey("StatusName")
                        .HasName("tournament_statuses_pkey");

                    b.ToTable("tournament_statuses", (string)null);
                });

            modelBuilder.Entity("MCT.Models.TournamentTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Placement")
                        .HasColumnType("integer")
                        .HasColumnName("placement");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.Property<int?>("TournamentId")
                        .HasColumnType("integer")
                        .HasColumnName("tournament_id");

                    b.HasKey("Id")
                        .HasName("tournament_teams_pkey");

                    b.HasIndex("TeamId");

                    b.HasIndex("TournamentId");

                    b.ToTable("tournament_teams", (string)null);
                });

            modelBuilder.Entity("MCT.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("users_pkey");

                    b.HasIndex("Role");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MCT.Models.UserRole", b =>
                {
                    b.Property<string>("RoleName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleName")
                        .HasName("user_roles_pkey");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("MCT.Models.Match", b =>
                {
                    b.HasOne("MCT.Models.MatchType", "MatchTypeNavigation")
                        .WithMany("Matches")
                        .HasForeignKey("MatchType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("matches_match_type_fkey");

                    b.HasOne("MCT.Models.Team", "TeamA")
                        .WithMany("MatchTeamAs")
                        .HasForeignKey("TeamAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("matches_team_a_id_fkey");

                    b.HasOne("MCT.Models.Team", "TeamB")
                        .WithMany("MatchTeamBs")
                        .HasForeignKey("TeamBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("matches_team_b_id_fkey");

                    b.HasOne("MCT.Models.Tournament", "Tournament")
                        .WithMany("Matches")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("matches_tournament_id_fkey");

                    b.HasOne("MCT.Models.Team", "Winner")
                        .WithMany("MatchWinners")
                        .HasForeignKey("WinnerId")
                        .HasConstraintName("matches_winner_id_fkey");

                    b.Navigation("MatchTypeNavigation");

                    b.Navigation("TeamA");

                    b.Navigation("TeamB");

                    b.Navigation("Tournament");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("MCT.Models.Payment", b =>
                {
                    b.HasOne("MCT.Models.PaymentStatus", "StatusNavigation")
                        .WithMany("Payments")
                        .HasForeignKey("Status")
                        .HasConstraintName("payments_status_fkey");

                    b.HasOne("MCT.Models.Ticket", "Ticket")
                        .WithMany("Payments")
                        .HasForeignKey("TicketId")
                        .HasConstraintName("payments_ticket_id_fkey");

                    b.Navigation("StatusNavigation");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("MCT.Models.Player", b =>
                {
                    b.HasOne("MCT.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("players_team_id_fkey");

                    b.HasOne("MCT.Models.User", "User")
                        .WithMany("Players")
                        .HasForeignKey("UserId")
                        .HasConstraintName("players_user_id_fkey");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MCT.Models.Stat", b =>
                {
                    b.HasOne("MCT.Models.Match", "Match")
                        .WithMany("Stats")
                        .HasForeignKey("MatchId")
                        .HasConstraintName("stats_match_id_fkey");

                    b.HasOne("MCT.Models.Player", "Player")
                        .WithMany("Stats")
                        .HasForeignKey("PlayerId")
                        .HasConstraintName("stats_player_id_fkey");

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MCT.Models.Ticket", b =>
                {
                    b.HasOne("MCT.Models.TicketStatus", "StatusNavigation")
                        .WithMany("Tickets")
                        .HasForeignKey("Status")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tickets_status_fkey");

                    b.HasOne("MCT.Models.Tournament", "Tournament")
                        .WithMany("Tickets")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tickets_tournament_id_fkey");

                    b.HasOne("MCT.Models.User", "User")
                        .WithMany("Tickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tickets_user_id_fkey");

                    b.Navigation("StatusNavigation");

                    b.Navigation("Tournament");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MCT.Models.Tournament", b =>
                {
                    b.HasOne("MCT.Models.TournamentStatus", "StatusNavigation")
                        .WithMany("Tournaments")
                        .HasForeignKey("Status")
                        .HasConstraintName("tournaments_status_fkey");

                    b.Navigation("StatusNavigation");
                });

            modelBuilder.Entity("MCT.Models.TournamentTeam", b =>
                {
                    b.HasOne("MCT.Models.Team", "Team")
                        .WithMany("TournamentTeams")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("tournament_teams_team_id_fkey");

                    b.HasOne("MCT.Models.Tournament", "Tournament")
                        .WithMany("TournamentTeams")
                        .HasForeignKey("TournamentId")
                        .HasConstraintName("tournament_teams_tournament_id_fkey");

                    b.Navigation("Team");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("MCT.Models.User", b =>
                {
                    b.HasOne("MCT.Models.UserRole", "RoleNavigation")
                        .WithMany("Users")
                        .HasForeignKey("Role")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("users_role_fkey");

                    b.Navigation("RoleNavigation");
                });

            modelBuilder.Entity("MCT.Models.Match", b =>
                {
                    b.Navigation("Stats");
                });

            modelBuilder.Entity("MCT.Models.MatchType", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("MCT.Models.PaymentStatus", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("MCT.Models.Player", b =>
                {
                    b.Navigation("Stats");
                });

            modelBuilder.Entity("MCT.Models.Team", b =>
                {
                    b.Navigation("MatchTeamAs");

                    b.Navigation("MatchTeamBs");

                    b.Navigation("MatchWinners");

                    b.Navigation("Players");

                    b.Navigation("TournamentTeams");
                });

            modelBuilder.Entity("MCT.Models.Ticket", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("MCT.Models.TicketStatus", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("MCT.Models.Tournament", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Tickets");

                    b.Navigation("TournamentTeams");
                });

            modelBuilder.Entity("MCT.Models.TournamentStatus", b =>
                {
                    b.Navigation("Tournaments");
                });

            modelBuilder.Entity("MCT.Models.User", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("MCT.Models.UserRole", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
